### ISSUE TITLE
Database Structure

### ISSUE THREAD

**Issue by alexander-schranz** [pucene/PuceneDoctrineBundle#1]
```
    +-------------+ 1   n +-------------+
    |   Indexes   |-------|  Mappings   |
    +------+------+       +------+-------+
           | 1                   | 1
           |                     |
           |                     |
           |                     |
           | n                   | n
    +------+------+ 1   n +------+------+ 1   n +-------------+ n   1 +-------------+
    |  Documents  |-------|   Fields    |-------|   Tokens    |-------|    Terms    |
    +-------------+       +-------------+       +-------------+       +-------------+
```

**Indexes**

 - name (string)

**Documents**

 - id (string)
 - type (string)
 - document (text)
 - index_id (string)

**Mappings**

 - id (integer)
 - name(string)
 - analyzed(boolean)?
 - analyzer(string)?

**Fields**

 - id (integer)
 - document_id (string)
 - name (string)
 - value (text)?

**Token**

 - id (integer)
 - token_id (integer)
 - field_id (integer)
 - position (string)

**Term**

 - id (integer)
 - value (string) (unique)

**TODO**

 - [ ] Table encoding?

**Comment by alexander-schranz** [comment]
@wachterjohannes If we add an additional table for unique token we should decide based on some benchmark tests.

**Comment by alexander-schranz** [comment]
@wachterjohannes the table encoding of the token table I think depends on the used analyzer. So the analyzer should set the encoding of the token table.

**Comment by wachterjohannes** [comment]
the table structure looks good. but the encoding can not be set by the analyzer. the analyzer depends on the field ... if we cannot fix the encoding (e.g. utf8) we have to create multiple tables for  each encoding.

**Comment by wachterjohannes** [comment]
additionally the document maybe should know his mapping (over type name or direct relation to mapping)

**Comment by alexander-schranz** [comment]
@wachterjohannes should not the field know about the mapping? Is the mapping for a field title not the same for all types of documents?

**Comment by wachterjohannes** [comment]
hmm thats right ... i thought about performance. but i dont think that this makes sense.
